#!/usr/bin/env python3

from pathlib import Path
import texercise
import argparse

version_groups = ('major', 'minor', 'micro')

parser = argparse.ArgumentParser()
group = parser.add_mutually_exclusive_group(required=True)
for name in version_groups:
    group.add_argument('--{}'.format(name), action='store_true', default=False)

args = parser.parse_args()

current_version = texercise.parse_version(texercise.__version__)
assert len(current_version) == 3
new_version = None
for i, name in enumerate(version_groups):
    if getattr(args, name):
        new_version = (*current_version[:i], current_version[i] + 1, *([0] * (2 - i)))
        break
assert new_version is not None
new_version_str = ".".join(map(str, new_version))
version_fp = Path(__file__).parent / 'texercise' / 'version.py'
with version_fp.open('w') as f:
    f.write("__version__ = '{}'".format(new_version_str))
print(new_version_str)
